<!doctype html> <html class="no-js"> <head> <meta charset="utf-8"> <title>My Animal Shelter</title> <meta name="description" content="animal shelter for cats and dogs"> <meta name="viewport" content="width=device-width"> <meta name="robots" content="index,follow"> <!-- Place favicon.ico and apple-touch-icon.png in the root directory --> <link rel="stylesheet" href="styles/vendor.e8193921.css"> <link rel="stylesheet" href="styles/main.f32cd502.css">  <body ng-app="animalShelterApp"> <div class="body-wrapper"> <!--[if lt IE 7]>
         <p class="browsehappy">
         You are using an <strong>outdated</strong> browser.
         Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your
         experience.
         </p>
      <![endif]--> <!-- Top Banner and Navigation Bar --> <div class="row"> <div class="medium-12 large-12 columns"> <img src="images/homepage_banner.6289c452.jpg" class="homepage-banner" alt="homepage banner"> <nav class="top-bar" data-topbar role="navigation"> <ul class="title-area"> <li class="name"> <h1><a href="">Animal Shelter</a></h1> </li> <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu"
                  to just have icon alone --> <li class="toggle-topbar menu-icon"><a href=""><span>Menu</span></a></li> </ul> <section class="top-bar-section"> <ul class="right" ng-controller="NavCtrl"> <li> <a ng-href="#/" ng-click="activeMenu.item = 1" ng-class="{'active-item': activeMenu.item == 1}">Home</a> </li> <li> <a ng-href="#/adopt" ng-click="activeMenu.item = 2" ng-class="{'active-item': activeMenu.item == 2}">Find</a> </li> <li> <a ng-href="#/volunteer" ng-click="activeMenu.item = 3" ng-class="{'active-item': activeMenu.item == 3}">Volunteer</a> </li> <li> <a ng-href="#/events" ng-click="activeMenu.item = 4" ng-class="{'active-item': activeMenu.item == 4}">Events</a> </li> <li> <a ng-href="#/contact" ng-click="activeMenu.item = 5" ng-class="{'active-item': activeMenu.item == 5}">Contact Us</a> </li> <li> <a ng-href="#/about" ng-click="activeMenu.item = 6" ng-class="{'active-item': activeMenu.item == 6}">About Us</a> </li> </ul> </section> </nav> </div> </div> <div class="row"> <!-- Angular View --> <div class="medium-12 large-12 column"> <div ng-view></div> </div> </div> <!-- End Angular View --> <br><br> <div class="row"> <!-- Footer Row --> <div class="medium-12 large-12 columns"> <div class="footer-wrap"> <div class="large-12 columns"><br> <ul class="left footer-links"> <li><a href="#/">Home</a></li> <li><a href="#/adopt">Find</a></li> <li><a href="">Volunteer</a></li> <li><a href="#/events">Events</a></li> <li><a href="">Donate</a></li> <li><a href="#/about">About Us</a></li> <li><a href="#/contact">Contact US</a></li> </ul> <ul class="right social-icons"> <li><a href="#" class="fa fa-lg fa-facebook"></a></li> <li><a href="#" class="fa fa-lg fa-youtube"></a></li> <li><a href="#" class="fa fa-lg fa-instagram"></a></li> <li><a href="#" class="fa fa-lg fa-twitter"></a></li> </ul> </div> <div class="large-12 columns"> <p class="copyright-credits">&copy 2015 Copyrighted. Designed and Developed by <a href="http://www.danilonavas.net" target="blank">D.Navas</a> and D.Silver. </p> </div> </div> <!-- End footer-wrap --> </div> <!-- End Columns --> </div> <!-- End Footer Row --> </div> <!-- End body-wrapper --> <!--[if lt IE 9]>
      <script src="scripts/oldieshim.c9f59ded.js"></script>
      <![endif]--> <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script> <script src="scripts/vendor.13468289.js"></script> <script src="scripts/scripts.5d98c698.js"></script> <script>// Start Zurb Foundation
         $(document).foundation();</script>  