<!doctype html> <html class="no-js"> <head> <meta charset="utf-8"> <title></title> <meta name="description" content="animal shelter for cats and dogs"> <meta name="viewport" content="width=device-width"> <meta name="robots" content="index,follow"> <!-- Place favicon.ico and apple-touch-icon.png in the root directory --> <link rel="stylesheet" href="styles/vendor.666e9843.css"> <link rel="stylesheet" href="styles/main.211927aa.css">  <body ng-app="animalShelterApp"> <!--[if lt IE 7]>
         <p class="browsehappy">You are using an <strong>outdated</strong> browser.
         Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
      <![endif]--> <!-- Top Banner and Navigation Bar --> <div class="row"> <div class="medium-12 large-12 columns"> <img src="images/homepage_banner.6289c452.jpg" alt="homepage banner"> <nav class="top-bar" data-topbar role="navigation"> <ul class="title-area"> <li class="name"> <h1><a href="">Animal Shelter</a></h1> </li> <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone --> <li class="toggle-topbar menu-icon"><a href=""><span>Menu</span></a></li> </ul> <section class="top-bar-section"> <ul class="right"> <li class=""><a ng-href="#/">Home</a></li> <li class=""><a ng-href="">Adopt</a></li> <li class=""><a ng-href="">Volunteer</a></li> <li class=""><a ng-href="">Events</a></li> <li><a ng-href="#/about">About Us</a></li> <li><a ng-href="">Contact Us</a></li> </ul> </section> </nav> </div> </div> <!-- Main View Row --> <div class="row"> <div class="medium-12 large-12 columns"> <div ng-view=""></div> </div> </div> <!-- Footer Row --> <br> <div class="row"> <div class="medium-12 large-12 columns"> <div class="footer-wrap"> <div class="large-12 columns"><br> <ul class="left footer-links"> <li><a href="">Home</a></li> <li><a href="">Adopt</a></li> <li><a href="">Volunteer</a></li> <li><a href="">Events</a></li> <li><a href="">Donate</a></li> <li><a href="">About Us</a></li> <li><a href="">Contact US</a></li> </ul> <ul class="right social-icons"> <li><a href="#" class="fa fa-lg fa-facebook"></a></li> <li><a href="#" class="fa fa-lg fa-youtube"></a></li> <li><a href="#" class="fa fa-lg fa-instagram"></a></li> <li><a href="#" class="fa fa-lg fa-twitter"></a></li> </ul> </div> <div class="large-12 columns"> <p class="copyright-credits">&copy 2015 Copyrighted. Designed and Developed by <a href="http://www.danilonavas.net" target="blank">D.Navas</a> and D.Silver. </p> </div> </div> </div> </div> <!-- Google Analytics: change UA-XXXXX-X to be your site's ID --> <script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
       (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
       })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

       ga('create', 'UA-XXXXX-X');
       ga('send', 'pageview');</script> <!--[if lt IE 9]>
      <script src="scripts/oldieshim.76f279db.js"></script>
      <![endif]--> <script src="scripts/vendor.53427476.js"></script> <script src="scripts/scripts.690c0488.js"></script> <!-- Start Foundation --> <script>$(document).foundation();</script> <!--  -->  